### ISSUE TITLE
Gas limit issue

### ISSUE THREAD

**Issue by Hex772** [rhiroshi/sunflower-farmers-bot#7]
Hi, do you know why sometimes i get the following error and the transaction doesn't go through?. Sounds like it has something to do with the createdAt time of events but i'm not sure where the problem could be

` at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: EVENT_IN_FUTURE`

**Comment by nbstrong** [comment]
Yeah happens because the "plant time" is less than the block timestamp.

https://github.com/rhiroshi/sunflower-farmers-bot/blob/e83d85ee831b6752f37cb4219728d012a320f2fc/contracts/Farm.sol#L308

I just set the delay lower and let it retry again. 

I'd like to fix it but it's low priority because its not breaking.

**Comment by Hex772** [comment]
Thanks for the explanation, that makes sense. Regarding the plant time, shouldn't there be a small difference in time between the slots's plant time to make it look more legit (i think the original repo had something like this) or do you think it doesn't really matter?

**Comment by nbstrong** [comment]
Looking legit doesn't matter at all.
